package entities;

// Generated Apr 26, 2015 9:45:15 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MenuId generated by hbm2java
 */
@Embeddable
public class MenuId implements java.io.Serializable {

	private int idMenu;
	private int idProduit;

	public MenuId() {
	}

	public MenuId(int idMenu, int idProduit) {
		this.idMenu = idMenu;
		this.idProduit = idProduit;
	}

	@Column(name = "id_menu", nullable = false)
	public int getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(int idMenu) {
		this.idMenu = idMenu;
	}

	@Column(name = "id_produit", nullable = false)
	public int getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(int idProduit) {
		this.idProduit = idProduit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MenuId))
			return false;
		MenuId castOther = (MenuId) other;

		return (this.getIdMenu() == castOther.getIdMenu())
				&& (this.getIdProduit() == castOther.getIdProduit());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMenu();
		result = 37 * result + this.getIdProduit();
		return result;
	}

	@Override
	public String toString() {
		return "MenuId [idMenu=" + idMenu + ", idProduit=" + idProduit + "]";
	}

}
