package com.dju.entities;

// Generated Apr 17, 2015 5:26:36 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "Client", catalog = "j2ee")
public class Client implements java.io.Serializable {

	private Integer idCli;
	private Panier panier;
	private String nomCli;
	private String prenomCli;
	private String adresseCli;
	private Long telCli;
	private String mdpCli;
	private String mailCli;
	private Date datenaiss;
	private Set<Panier> paniers = new HashSet<Panier>(0);
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public Client() {
	}

	public Client(Panier panier, String nomCli, String prenomCli,
			String adresseCli, Long telCli, String mdpCli, String mailCli,
			Date datenaiss, Set<Panier> paniers, Set<Commande> commandes) {
		this.panier = panier;
		this.nomCli = nomCli;
		this.prenomCli = prenomCli;
		this.adresseCli = adresseCli;
		this.telCli = telCli;
		this.mdpCli = mdpCli;
		this.mailCli = mailCli;
		this.datenaiss = datenaiss;
		this.paniers = paniers;
		this.commandes = commandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_cli", unique = true, nullable = false)
	public Integer getIdCli() {
		return this.idCli;
	}

	public void setIdCli(Integer idCli) {
		this.idCli = idCli;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_panier")
	public Panier getPanier() {
		return this.panier;
	}

	public void setPanier(Panier panier) {
		this.panier = panier;
	}

	@Column(name = "nom_cli", length = 25)
	public String getNomCli() {
		return this.nomCli;
	}

	public void setNomCli(String nomCli) {
		this.nomCli = nomCli;
	}

	@Column(name = "prenom_cli", length = 25)
	public String getPrenomCli() {
		return this.prenomCli;
	}

	public void setPrenomCli(String prenomCli) {
		this.prenomCli = prenomCli;
	}

	@Column(name = "adresse_cli", length = 25)
	public String getAdresseCli() {
		return this.adresseCli;
	}

	public void setAdresseCli(String adresseCli) {
		this.adresseCli = adresseCli;
	}

	@Column(name = "tel_cli", precision = 10, scale = 0)
	public Long getTelCli() {
		return this.telCli;
	}

	public void setTelCli(Long telCli) {
		this.telCli = telCli;
	}

	@Column(name = "mdp_cli", length = 25)
	public String getMdpCli() {
		return this.mdpCli;
	}

	public void setMdpCli(String mdpCli) {
		this.mdpCli = mdpCli;
	}

	@Column(name = "mail_cli", length = 25)
	public String getMailCli() {
		return this.mailCli;
	}

	public void setMailCli(String mailCli) {
		this.mailCli = mailCli;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datenaiss", length = 10)
	public Date getDatenaiss() {
		return this.datenaiss;
	}

	public void setDatenaiss(Date datenaiss) {
		this.datenaiss = datenaiss;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Panier> getPaniers() {
		return this.paniers;
	}

	public void setPaniers(Set<Panier> paniers) {
		this.paniers = paniers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
