package com.dju.entities;

// Generated Apr 24, 2015 5:08:28 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "Menu", catalog = "j2ee")
// @PrimaryKeyJoinColumn(name = "idProduit")
public class Menu implements java.io.Serializable { //extends Produit {

	private MenuId id;
	private Produit produit;

	public Menu() {
	}

	public Menu(MenuId id, Produit produit) {
		this.id = id;
		this.produit = produit;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idMenu", column = @Column(name = "id_menu", nullable = false)),
			@AttributeOverride(name = "idProduit", column = @Column(name = "id_produit", nullable = false)) })
	public MenuId getId() {
		return this.id;
	}

	public void setId(MenuId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produit", nullable = false, insertable = false, updatable = false)
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Override
	public String toString() {
		return "Menu [id=" + id + "]";
	}

}
