package com.dju.entities;

// Generated Apr 17, 2015 5:26:36 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Panier generated by hbm2java
 */
@Entity
@Table(name = "Panier", catalog = "j2ee")
public class Panier implements java.io.Serializable {

	private Integer idPanier;
	private Client client;
	private Set<Client> clients = new HashSet<Client>(0);

	public Panier() {
	}

	public Panier(Client client, Set<Client> clients) {
		this.client = client;
		this.clients = clients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_panier", unique = true, nullable = false)
	public Integer getIdPanier() {
		return this.idPanier;
	}

	public void setIdPanier(Integer idPanier) {
		this.idPanier = idPanier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cli")
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "panier")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

}
