package com.dju.entities;

// Generated Apr 17, 2015 5:26:36 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlatId generated by hbm2java
 */
@Embeddable
public class PlatId implements java.io.Serializable {

	private int idPlat;
	private int idProduit;

	public PlatId() {
	}

	public PlatId(int idPlat, int idProduit) {
		this.idPlat = idPlat;
		this.idProduit = idProduit;
	}

	@Column(name = "id_plat", nullable = false)
	public int getIdPlat() {
		return this.idPlat;
	}

	public void setIdPlat(int idPlat) {
		this.idPlat = idPlat;
	}

	@Column(name = "id_produit", nullable = false)
	public int getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(int idProduit) {
		this.idProduit = idProduit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlatId))
			return false;
		PlatId castOther = (PlatId) other;

		return (this.getIdPlat() == castOther.getIdPlat())
				&& (this.getIdProduit() == castOther.getIdProduit());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPlat();
		result = 37 * result + this.getIdProduit();
		return result;
	}

}
