package com.dju.entities;

// Generated Apr 24, 2015 5:08:28 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Plat generated by hbm2java
 */
@Entity
@Table(name = "Plat", catalog = "j2ee")
public class Plat implements java.io.Serializable {

	private PlatId id;
	private Produit produit;
	private String typeCuisine;
	private Integer nbPers;
	private boolean chaud;
	private String typePlat;

	public Plat() {
	}

	public Plat(PlatId id, Produit produit) {
		this.id = id;
		this.produit = produit;
	}

	public Plat(PlatId id, Produit produit, String typeCuisine, Integer nbPers,
			boolean chaud, String typePlat) {
		this.id = id;
		this.produit = produit;
		this.typeCuisine = typeCuisine;
		this.nbPers = nbPers;
		this.chaud = chaud;
		this.typePlat = typePlat;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idPlat", column = @Column(name = "id_plat", nullable = false)),
			@AttributeOverride(name = "idProduit", column = @Column(name = "id_produit", nullable = false)) })
	public PlatId getId() {
		return this.id;
	}

	public void setId(PlatId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produit", nullable = false, insertable = false, updatable = false)
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Column(name = "type_cuisine", length = 25)
	public String getTypeCuisine() {
		return this.typeCuisine;
	}

	public void setTypeCuisine(String typeCuisine) {
		this.typeCuisine = typeCuisine;
	}

	@Column(name = "nb_pers")
	public Integer getNbPers() {
		return this.nbPers;
	}

	public void setNbPers(Integer nbPers) {
		this.nbPers = nbPers;
	}

	@Column(name = "chaud")
	public boolean isChaud() {
		return this.chaud;
	}

	public void setChaud(boolean chaud) {
		this.chaud = chaud;
	}

	@Column(name = "type_plat", length = 25)
	public String getTypePlat() {
		return this.typePlat;
	}

	public void setTypePlat(String typePlat) {
		this.typePlat = typePlat;
	}

	@Override
	public String toString() {
		return "Plat [id=" + id + ", typeCuisine=" + typeCuisine + ", nbPers="
				+ nbPers + ", chaud=" + chaud + ", typePlat=" + typePlat + "]";
	}

}
