package com.dju.entities;

// Generated Apr 17, 2015 5:26:36 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Traiteur generated by hbm2java
 */
@Entity
@Table(name = "Traiteur", catalog = "j2ee")
public class Traiteur implements java.io.Serializable {

	private Integer idTraiteur;
	private String nomTraiteur;

	public Traiteur() {
	}

	public Traiteur(String nomTraiteur) {
		this.nomTraiteur = nomTraiteur;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_traiteur", unique = true, nullable = false)
	public Integer getIdTraiteur() {
		return this.idTraiteur;
	}

	public void setIdTraiteur(Integer idTraiteur) {
		this.idTraiteur = idTraiteur;
	}

	@Column(name = "nom_traiteur", length = 25)
	public String getNomTraiteur() {
		return this.nomTraiteur;
	}

	public void setNomTraiteur(String nomTraiteur) {
		this.nomTraiteur = nomTraiteur;
	}

}
